### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by Nathan22211** [grondag/doomtree#1]
from the crash I got in the launcher it was at the entry point 'main' `---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 10/28/19 6:22 AM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:45)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.method_1503(class_310.java:445)
	at net.minecraft.class_310.method_1514(class_310.java:394)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:178)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	Suppressed: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/particle/v1/FabricParticleTypes
		at grondag.fermion.registrar.Registrar.particle(Registrar.java:138)
		at grondag.doomtree.registry.DoomParticles.<clinit>(DoomParticles.java:10)
		at grondag.doomtree.DoomTree.onInitialize(DoomTree.java:37)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$1742/1560853538.accept(Unknown Source)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.lambda$logErrors$0(EntrypointUtils.java:38)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils$$Lambda$1743/1874414646.accept(Unknown Source)
		at java.util.ArrayList.forEach(ArrayList.java:1249)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:36)
		... 11 more
	Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.particle.v1.FabricParticleTypes
		at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
		at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		... 19 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:45)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.method_1503(class_310.java:445)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.class_310.method_1514(class_310.java:394)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:178)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5051849352 bytes (4817 MB) / 7851737088 bytes (7488 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		adorn: Adorn 1.5.0+1.14.4
		allium: Allium Peripherals 0.1.0
		allure: Allure 1.1.5
		amethystmod: Amethyst Mod 1.2.0
		aquarius: Aquarius 1.4.0+1.14.4
		artifice: Artifice 0.3.5
		autoconfig1: Auto Config v1 1.2.0+mc1.14.4
		autojson: Auto Json 1.14.4-1.1.0
		bambootweaks: Bamboo Tweaks 1.14.4-1.1.0
		bark: Tree Bark 1.1.0
		battle-towers: Battle Towers 1.1.2
		beachslimes: Beach Slimes 1.3.0+mc1.14.4
		berrysmod: Berry's Mod 1.1.3
		block_factory: Block Factory 0.4.1
		blockus: Blockus 1.2.0
		blue_endless_jankson: jankson 1.1.2
		carpet: Carpet Mod in Fabric 1.2.0
		carpet-extra: Carpet Extra 1.2.0
		chunkactivator: Chunk Activator 1.2.0+mc1.14.4
		clippys_tippies: Clippie's Tippies Â® 1.0.0
		cloth: Cloth Events 0.6.0
		cloth-config: Cloth Config 0.2.4+build.17
		cloth-config2: Cloth Config v2 1.3
		composableautomation: Composable Automation 0.6.0+mc1.14.4
		computercraft: CC:T for Fabric 1.83.2+build.8
		cookies: Cookies 1.14.4-1.0.0.1-universal
		cotton: Cotton 1.0.0-rc.3
		cotton-cauldron: Cotton Cauldron 1.0.0-rc.1
		cotton-client-commands: Cotton Client Commands 0.4.2+1.14.3-SNAPSHOT
		cotton-commons: Cotton Commons 1.0.0-rc.3
		cotton-config: Cotton Config 1.0.0-rc.1
		cotton-datapack: Cotton Datapack 1.0.0-rc.1
		cotton-logging: Cotton Logging 1.0.0-rc.1
		cotton-player-events: Cotton Player Events 1.0.0-rc.2
		cotton-resources: Cotton Resources 1.4.1+1.14.4
		crafty: Crafty 0.3.3+1.14.1
		creativebuttonmover: Creative Button Mover 0.1.1+1.14.4
		creeperspores: Creeper Spores 1.2.1
		customrecord: Custom Records 1.0.2
		doomtree: The Doom Tree 0.2.21
		dynagear: DynaGear 1.3.1+1.14.4
		eggsplus: Eggs Plus 1.1.0
		emerald: Emerald tools 1.8.1
		enchantedtooltips: Enchanted ToolTips 1.1.0
		endreborn: End: Rebellion 1.0
		ep-addon: Extra Pieces Addon 1.0.2
		expandedstorage: ExpandedStorage 3.6.29+1.14.4
		extradiscs: ExtraDiscs 1.1.0+build.6
		extradoors: ExtraDoors 1.2.0
		extrapieces: Extra Pieces 2.8.3
		fabric: Fabric API 0.3.3+build.234-1.14
		fabric-api-base: fabric-api-base 0.1.0+5914746342
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.0+591e97ae42
		fabric-commands-v0: Fabric Commands (v0) 0.1.1+591e97ae42
		fabric-containers-v0: Fabric Containers (v0) 0.1.2+591e97ae42
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.1+591e97ae42
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.1+591e97ae42
		fabric-dimensions-v1: fabric-dimensions-v1 0.1.0+369ab22e42
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.1.1+591e97ae42
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.1+591e97ae42
		fabric-item-groups-v0: fabric-item-groups-v0 0.1.0+1e69a0a542
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+591e97ae42
		fabric-language-kotlin: Fabric Language Kotlin 1.3.50+build.1
		fabric-language-scala: Fabric Language Scala 0.2.0.9
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.0+591e97ae42
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.0+591e97ae42
		fabric-models-v0: Fabric Models (v0) 0.1.0+591e97ae42
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.1.1+591e97ae42
		fabric-networking-v0: fabric-networking-v0 0.1.3+9f55aa7042
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.1+591e97ae42
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.2+591e97ae42
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.1.1+591e97ae42
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.1.13+591e97ae42
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.0+591e97ae42
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.2+36f27aa342
		fabric-rendering-v0: Fabric Rendering (v0) 0.1.1+591e97ae42
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.3+591e97ae42
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.1+591e97ae42
		fabric-textures-v0: Fabric Textures (v0) 0.1.4+591e97ae42
		fabricdrawer: Fabric Drawer 1.1.1
		fabricloader: Fabric Loader 0.6.2+build.166
		faeriefire: Faerie Fire 1.0.1
		fermion: Fermion 1.3.86
		fermion-varia: Fermion Varia 1.3.86
		fiber2cloth: Fiber To Cloth 1.1.0
		flax: Flax 1.0.0
		function_api: Function API 1.2.2
		glassential: Glassential 1.14.4-1.1.0
		grindstone_books: Grindstone Books 1.0.0
		handystructures: Handy Structures 1.0.3
		hardstone_1730: Hardstone Mod 1.0.7
		heartofthecauldron: Heart of the Cauldron 1.1.0
		illuminations: Illuminations 0.3.0
		infinityfix: Infinity Fix 1.1.0
		jankson: Jankson 1.0.0+j1.1.2
		jargm: Just Another Redstone Gate Mod 1.0.1
		javax_vecmath_vecmath: vecmath 1.5.2
		ladderapi: Ladder API 1.14.4-1.1.0
		libblockattributes_core: LibBlockAttributes (Core) 0.4.10
		libblockattributes_items: LibBlockAttributes (Items) 0.4.10
		libcd: LibCapableData 1.5.0+1.14.4
		libgui: LibGui 1.3.2
		loot_editor: LootEditor 1.0.0-SNAPSHOT
		luminiferous_uplands: Luminiferous Uplands 1.1.1
		me_zeroeightsix_fiber: fiber 0.6.0-7
		minecraft: Minecraft 1.14.4
		miners_horizon: Miner's Horizon 1.5.0
		ml3lib: ML3 Library 1.1.1
		mm: Manningham Mills 1.7
		mobz: MobZ 1.7.4
		mooblooms: Mooblooms 1.0.1
		moreberries: More Berries 1.2.1
		mycraft: My Craft 1.2.4
		nbtcrafting: NBT Crafting 1.2.4+1.14.4
		netherthings: Nether Things 1.2.0
		nodami: No Damage Immunity (NoDamI) 1.14.4-0.2-fabric
		org_jetbrains_annotations: annotations 17.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.50
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.50
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.50
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.0
		org_jetbrains_kotlinx_kotlinx-serialization-runtime: kotlinx-serialization-runtime 0.12.0
		paintz: PaintZ 1.0
		pathsuggestion: Path Suggestion 0.2.0
		redstonebits: Redstone Bits 1.0.4+mc1.14.1
		redstoneutils: Redstone Utils 1.14.4-1.0.0
		reinstorage: Reinforced Storage 1.1.2
		roughlyenoughitems: Roughly Enough Items 3.1.2+build.12
		sde: Stackable Damage Enchants 1.0.1
		simplevoidworld: Simple Void World 1.0.0
		smartermending: Smarter Mending 1.1.0
		spatialcrafting: Spatial Crafting 1.2.0
		statement: Statement 1.1.0+1.14.4
		staticdata: Static Data 1.0.0
		stoneextended: Stone Extended 1.0.4
		stuffz: StuffZ 1.0.0
		terraform: Terraform 1.1.8+build.15
		terrestria: Terrestria 1.0.11+build.40
		tinyconfig: TinyConfig 1.1.2
		toughglass: Tough Glass 1.0.0
		towelette: Towelette 2.1.0+1.14.4
		traverse: Traverse 2.0.8+build.26
		trumpet-skeleton: Trumpet Skeleton 1.1.0
		tsb: Trapped Shulker Boxes 1.0.4
		vanilla-hammers: Vanilla Hammers 1.6.3
		vanilla-toolsets: Vanilla Toolsets 1.2.1
		vanillaecxavators: Vanilla Excavators 1.0.2
		variablepaxels: VariablePaxels 1.14.4-1.0.1
		verticalredstone: Vertical Redstone 1.0.1
		vmulti: Vanilla Multiblock API 1.0.1+1.14.4
		wildworld: Wild World 1.2.0
		woodmill: Woodmill 1.0.0
		working-scheduler: Working Scheduler 1.1.0
		zmod: AppleZ 1.3.0
	Launched Version: fabric-loader-0.6.2+build.166-1.14.4
	LWJGL: 3.2.2 build 10
	OpenGL: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: extrapieces:ep_assets, dynagear:dynagear_assets, vanilla, file/[16x16]Dirty+Bricks+V1.1.2+For+MC+1.13 (1).zip, file/Wallpapers.zip, file/[16x16]Plain+Wood+Doors+V1.0.2+For+MC+1.13.zip, file/MechResources_v2.1.0.zip, file/Undermagic RP, file/Target Block v1.0 [Resource Pack].zip
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: <unknown>`

**Comment by grondag** [comment]
Update to the most recent Fabric API. The version you have is quite old and doesn't include the particle API this mod uses.
